name: Fmt

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Fmt
        run: cargo fmt --verbose