name: Test

on: [push]

jobs:

  fmt:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test
        run: cargo test --verbose
